### ISSUE TITLE
IHM : Definition + Implémentation menus

### ISSUE THREAD

**Issue by unice-etu-gom** [itii-p17-projet-elec/microcontroller-main#3]
- [x] Définir l'arborescence des différents menus ;
- [x] Les implémenter dans la FSM Display (CF. #2 ).

Arborescence des menus :
+ [x] Écran d'accueil
    + [x] Menu View
        + [x] Affichage de la Température ambiante
        + [x] Affichage de la Température de la batterie
        + [x] Affichage du Courant de charge de la batterie
        + [x] Affichage du Courant de décharge de la batterie
        + [x] Affichage du Courant consommé par la batterie
        + [x] Affichage de la Tension de la batterie
        + [x] Affichage du Pourcentage de charge de la batterie
        + [x] Retour au menu précédent
    + [ ] Menu Config
        + [x] Configuration période d'émission mesures
        + [x] Alerte température ambiante : Config seuil min
        + [ ] Alerte température ambiante : Config seuil max
        + [x] Retour au menu principal
    + [x] Retour au menu précédent

**Comment by unice-etu-gom** [comment]
Application de l'exigence itii-p17-projet-elec/documentation#10.

En relation avec les exigences suivantes :
+ itii-p17-projet-elec/documentation#12
+ itii-p17-projet-elec/documentation#13
+ itii-p17-projet-elec/documentation#14
+ itii-p17-projet-elec/documentation#17
+ itii-p17-projet-elec/documentation#18
+ itii-p17-projet-elec/documentation#19

**Comment by MaximeB5** [comment]
Arborescence du modèle visuel rattaché au LCD :
+ Écran d'accueil
    + Menu Config
    + Menu View
        + Affichage de la Température ambiante
        + Affichage de la Température de la batterie
        + Affichage du Courant de charge de la batterie
        + Affichage du Courant de décharge de la batterie
        + Affichage du Courant consommé par la batterie
        + Affichage de la Tension de la batterie
        + Affichage du Pourcentage de charge de la batterie
        + Retour au menu précédent
    + Retour au menu précédent

**Comment by unice-etu-gom** [comment]
Validation intégration sur LCD effectuée.

Corrections mineures effectuées, manque l'acquisition des différentes valeurs pour aller plus loin.

**Comment by unice-etu-gom** [comment]
Attention : [Voir dans cette issue](https://github.com/itii-p17-projet-elec/microcontroller-main/issues/9#issuecomment-492797245) si la liste des infos côté batterie est toujours d'actualité.
